name: Windows - LiteManager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/joyzone/lite_manager_win/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Connect to LiteManager
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat

      - name: Auto-Retrigger Workflow
        if: always()
        run: |
          $token = "${{ secrets.GITHUB_TOKEN }}"
          $headers = @{
            Authorization = "token $token"
            Accept        = "application/vnd.github.v3+json"
          }
          $body = '{"ref":"main"}'
          $url = "https://api.github.com/repos/${{ github.repository }}/actions/workflows/lite_manager_win_cloud_pc.yml/dispatches"
          Invoke-RestMethod -Uri $url -Method POST -Body $body -Headers $headers
